# Generated by Django 3.2 on 2021-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=25)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
