# Generated by Django 3.2 on 2021-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210506_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='workout',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
